// The rows of the controls help (openHelp in hud.ts), in the order it shows them: a key or an emoji, and
// what it does. A new control is a new row here.

import { IS_MAC } from './termkeys';

export const HELP_ROWS: readonly (readonly [string, string])[] = [
  ['W A S D', 'Walk (hold Shift to run)'],
  ['Space', 'Jump'],
  ['☕', 'Press E at the coffee machine in the kitchen for a minute of quicker walking and higher jumps. Three cups in a row gives you the jitters'],
  ['🧊', 'Press E at the fridge next to it for a cold bottle, a can or a snack: Helles, Radler, Spezi, Mate, a Brezn, a Leberkässemmel… It comes along wherever you go'],
  ['🎾', 'Across the street to the east, the padel hall: E at its glass doors goes in, E at the doors inside back out. Up the stairs on the gallery, E at the café counter for a coffee, an Apfelschorle or a slice of Käsekuchen. The coffees give you the kitchen machine’s buzz'], // fork
  ['⚽', 'Across the street, between the golf hole and the padel hall, the soccer hall: E at its doors goes in. E at the boards on the halfway line puts you in a team (a bib and a ring in its colour); run onto the ball to take it and dribble. Click (or Space) passes to the teammate you look at, hold to charge a shot where you look (look up to lift it), the right button (or C) lobs or chips; Shift sprints; Q (or Ctrl) slide-tackles: the ball first wins it, the legs first is a foul. E at the boards again leaves the pitch'], // fork
  ['Mouse', 'Look around in first person (click to capture the mouse, Esc to free it)'],
  ['Click / E', "Use what you look at: hire a worker, open its terminal, read a board, call a meeting in the meeting room, watch the TV or put a YouTube or Twitch stream on it, put a song on the jukebox, tee off from the balcony, sit on a couch, a beanbag, a chair or the balcony bench (walk off to get up)"],
  ['👥', 'Click someone under "In the office" to walk over to them (on another floor, you ride the elevator first). The line under their name says what they have open or where they are'],
  ['🛗', 'Every project is a floor: step into the elevator on the north wall and press E (or click the project name, top left) to go to another one or add a project. It goes down to the garage too, and back up from there'],
  ['🤖', 'An agent stands by the issues board, the PR board and the task queue. Press E at one and type what you want: it runs as an agent that knows that board. O there opens its terminal, X sends it home'],
  ['📝', 'The whiteboard on wheels between the desks and the lounge: press E to draw on it with everyone on your floor, live. What you draw stays up on the board'],
  ['🏁', 'The racing rig next to the arcade plays OFFICE GP: ↑ gas, ↓ brake, ← → steer, Space boost, R restart (a gamepad or wheel works too). Three laps, the fastest races and laps go on the building’s tables, and E there watches whoever is racing'],
  ['🕹️', 'The arcade cabinet in the lounge plays BLOCKFALL: arrows (or WASD) move and turn, Space drops, C holds, P pauses. Everyone on the floor sees your game on it, and E there watches whoever is playing. One of your workers needing input pauses it'],
  ['🎉', 'Whenever a pull request merges, the gong next to the PR board rings, confetti rains down all over the floor and every worker gets up on its desk for a quick dance. Walk up to the gong and press E to bang it yourself'],
  ['N', "Next worker that needs you: go to whoever has waited longest (needs input, or done and nobody's looked), and again for the next one. Arrows at the edge of the screen point to the ones out of sight"],
  ['🏀', 'The hoop on the west wall, by the exit door: E at the ball picks it up. Hold E (or the mouse, in first person) and let go when the meter is in the green to sink it. In first person it goes where you look. Q drops it. Everyone on your floor sees your shot'],
  ['🏎️', "The Lambos and Ferraris in the garage: E at one gets you behind the wheel, or beside whoever's driving it. W is the gas, S brakes and reverses, A and D steer, Space brakes, H honks and E gets you out. Everyone on your floor sees you drive by"],
  ['🚐', "Flogge's Bulli, backed into the garage's east corner: only its keyholders take the wheel, but anyone can ride along beside them. It's slow and soft, and its horn goes möp möp"],
  // flrnoh fork: the cinema (features/kino).
  ['🍿', 'Behind the office to the north-west, the cinema: real films (Blender open movies and silent classics) back to back in Saal 1, on the office clock, so everyone sees the same moment. E at the counter for popcorn, nachos or a cola, E at a seat to sit down (walk off to get up), E at the screen for the programme'],
  ['🎬', 'In the cinema’s small Saal 2, E at the lectern by the door puts on a YouTube or Twitch link for everyone in there, like the office TV; E at its screen watches it full screen'],
  // flrnoh fork: a day at the beach (features/beach).
  ['🍟', 'Down the scenic loop west of town, Sunset Beach: the Kiosk zur Möwe by the road is open. E at its counter and Uschi hands over Pommes rot-weiß, a Currywurst, a Fischbrötchen, ice cream, a coconut… all free. Ice cream gives you brain freeze, and mind the seagulls'],
  ['🏊', 'Walk into the sea off the beach (or jump off the end of the jetty, or its diving board) and you swim: W A S D, Shift faster, Space splashes. Stay inside the buoys. E at the ladder at the jetty’s end climbs out, or swim in until you can stand'],
  ['🚤', 'The jetskis and the motorboat at the jetty: E at one takes the helm (or a free seat). W A S D steer on the open water, Space slows down, H sounds the horn, E gets off onto the jetty when you’re alongside it, else into the water for a swim'],
  // flrnoh fork: the Baumarkt (features/baumarkt).
  ['🔨', 'A block north-east of the office, HAMMER & CO, the Baumarkt: walk in through the sliding doors. E at the tool wall for a drill, a cordless screwdriver, a hammer or a chainsaw (click to use it, Q to put it back; it stays in the hall), E at the paint counter to have a can shaken in your colour, E at a trolley to push it about (E or Q lets go; by the corral it rolls back in), E at Gabi’s till. Listen out for the PA'],
  ['🚜', 'The Baumarkt’s forklift: E gets on, W S drive, A D steer the rear wheels (the tail swings out), R or Space raise the forks, F or Shift lower them, H horn, E gets off. Drive the forks into a pallet and raise them to pick it up, lower them to the floor to set it down somewhere else. It beeps backing up'],
  // flrnoh fork: the sounds of the city (features/citysound).
  ['🔔', 'Down on the street the city is there to hear: the road and the cars going by, birds in the parks, people by the shops. The church on the park north-west of the office strikes the hours. ⚙️ → Sound & voice → Stadtgeräusche turns it off'],
  // flrnoh fork: the city's shops (features/shops).
  ['🏪', 'The shops on the ground floors round about are open: walk in through any door. A Bäckerei, a café, a pizzeria, an Apotheke, a florist, a bookshop, a kiosk, a bar, a Späti, a Döner, a toy shop, a record shop, a barber, a tattoo studio, a boutique and an optician, all over town. E at the counter: what you order is in your hand (everyone sees it) and comes along. The bar’s drinks go to your head, the Apotheke’s headache pill clears it, the café’s coffees give you the buzz'],
  ['💈', 'At the barber (Friseur) E at a chair: sit down and pick a new hair style, hair colour and beard. At the tattoo studio: a tattoo (motif and where), a piercing (silver or gold), or the laser to take one off. Everyone sees your new look'],
  ['☂️', 'Outside the café and the Döner: E at a chair to sit at a table in the sun (W A S D to get up). The shops close on the office clock: Bäckerei, Apotheke, florist and bookshop at 20:00, shutters down, door locked; the bar, the Döner, the kiosk and the Späti stay open late'], // flrnoh fork: shop fronts
  ['🧸', 'A toy from the toy shop in your hand: click (or E with nothing else to use) to play: the yo-yo, soap bubbles, the squeaky duck, a paper plane that glides off, a water pistol (a splash, nothing more), the teddy for a hug. A book or the paper: E to read it'],
  ['👗', 'At the boutique (Klamotten) E at a rack or in a changing cubicle (the curtain draws shut while you’re in): a hoodie, a shirt, a blazer, a leather jacket or a dress, its colour, trousers, a cap, beanie, hat or sun hat. At the optician (Optik) E at the wall of glasses: round, square, nerd, aviators or cat-eye, clear, dark or mirrored. Everyone sees it; the character window has it too'],
  ['🍨', 'Food round 2: at the Eisdiele E at the counter picks two or three scoops in a cone or a cup (or a Spaghettieis, an Eiskaffee): brain freeze guaranteed. At the Sushi-Bar E at the belt takes the plate passing in front of you, chopsticks and all. At the Metzgerei: a Leberkässemmel, a pair of Wiener, a Fleischpflanzerl'],
  ['🥫', 'The Supermarkt (a whole side of its building): E at the trolley bay by the door takes a trolley you push in front of you (everyone sees it, out onto the sidewalk too), E at a shelf, the fridges or the fruit stand puts something in, E at the checkout rings it up (beep, beep, a receipt; on the house), E with nothing to use lets go of it'],
  ['💿', 'In the record shop, E at a crate digs through the records (take one along), E at the listening station puts the headphones on: only you hear it, ✕, Esc or E takes them off'],
  // flrnoh fork: bikes, pets, laundry (features/ride).
  ['🚲', 'The Fahrradladen rents bikes (E at the counter): a Hollandrad, a Rennrad, a BMX or a Lastenrad, and you’re on it outside the door. W pedals, S brakes, A D steer, Space hops (the BMX jumps), H rings the bell, E gets off (E at it to get back on). Everyone sees you ride; walk into a bike shop to give it back'],
  ['🐠', 'The Zoohandlung: E at the counter for a goldfish in a bag of water, or a budgie that sits on your shoulder a few minutes (everyone sees it). The Waschsalon: E at a free washing machine starts a wash (the drum tumbles, about a minute), E at a plastic chair to sit and wait, E at the Automat for a drink or a snack'],
  // flrnoh fork: the Spielhalle and the Post (features/funshops).
  ['👾', 'The Spielhalle (neon sign): E at a cabinet plays BLOCKFALL just for you. E at the claw machine (Greifautomat): arrows or W A S D move the claw, Space drops it before the clock runs out; if it holds, the plush is yours to carry. Everyone near sees the claw go'],
  ['📸', 'The Spielhalle’s photo booth: E steps in, the curtain closes, pick a pose (the emotes) before each of four shots, and out comes a photo strip: download it as a PNG, and it’s in your hand too'],
  ['📮', 'The Post (yellow sign): E at the counter writes a postcard: a picture of the city on the front, a few lines on the back, to anyone in the office. They get it as a toast and a card at once if they’re in, else next time. Ten a day. E at the PO boxes looks for cards for you'],
  // flrnoh fork: the petrol station (features/tankstelle).
  ['⛽', 'FLOGGE OIL, the petrol station a block west of the office: drive a garage car (or the Bulli) up beside a pump and stop, then E fills it up (from behind the wheel, or standing at the pump). The pump counts the litres and euros, all on the house. Everyone on your floor sees the hose go in'],
  ['🧽', 'Its car wash: drive in off the forecourt, stop on the yellow marking and press E (or E at the terminal by the way in). Brushes, coloured foam, water and the dryer, about half a minute; stay put until the light goes green, then drive out the north door shiny. Standing in there while it sprays gets you soaked'],
  // flrnoh fork: traffic lights and the city bus (world/town/lights.ts, features/citybus).
  ['🚦', 'The busier crossings in town have traffic lights: the city’s cars stop at the line on red, and the passers-by wait for the green man. Everyone sees the same phase. The garage’s cars don’t have to stop, but run a red at more than 30 km/h and the speed camera flashes: geblitzt!'],
  ['🚌', 'Two city bus lines (7 and 12) drive loops through town past the office and stop at the bus stops. E at an open door gets you on, and you ride along inside; E again gets you off at the next stop (straight away while the doors are open)'],
  ['🛒', 'The station’s shop: walk in through the sliding door and press E at the counter for a coffee to go (the kitchen machine’s buzz), a Schokoriegel, Chips, an Energy-Drink, a Bockwurst or the paper'],
  ['🍸', 'The elevator goes up to the rooftop bar: a DJ playing drum and bass under the lights, and the city all around. Press E at the bar for a drink (it goes to your head for a bit) and at the DJ booth to put on a DJ set from YouTube, SoundCloud or Mixcloud for everyone up there (H there blows the air horn). The lights, the LED wall and the DJ move to the set\'s own beat; if they\'re off it, tap the tempo in at the booth'],
  ['🎯', 'Up on the roof, in the corner past the DJ: a dart board and an axe-throwing lane. E at either steps up to the line. The mouse (or the arrow keys) aims, and your hand wanders more after a few drinks. Hold Space (or the mouse button) and let go in the green: three darts a visit, five axes a round, chalked up for everyone up there. E steps back'],
  ['Drag / wheel', 'Orbit and zoom the camera in third person'],
  ['P', 'Prompt: give a task to a new or existing worker at the desk you face'],
  ['C', 'Changes: what the worker at the desk you face changed — files and diff, commit, discard, open a PR'],
  ['B', 'Open a shared shell (dev servers, git, tests) at an empty desk'],
  ['R', 'Resume a sleeping worker'],
  ['X', 'Send a worker home (frees the desk)'],
  ['L', 'Hang a big sign over the desk you face ("Operations", "Code cleanup"), or change or take down the one there'],
  ['🚧', 'Room to grow: E at the sign on the north wall past the gong knocks through into a back office with 2 more desks, and again for 2 more. The same sign walls a row back up'],
  ['F', 'Hang a picture from the web on a wall. Look at a picture and press E to move, edit or take it down'],
  ['Q', 'Put back the issue card in your hands (E at a note on the issues board, or ✋ Pick it up in an issue; then E at an empty desk, a worker or the queue board), or drop the basketball'],
  ['🐶', 'Walk up to the office dog and press E to pet it. When a worker needs input, it runs to that desk and barks. Name it in ⚙️ Settings'],
  ['O', 'Open a pull request for a worker on its own branch, or see the one it has'],
  ['T', 'Chat'],
  ['G / 1–6', 'Emote: hold G, point at one and let go (or tap G and click one), or press 1–6: wave, thumbs up, clap, dance, point, facepalm. Everyone on your floor sees it'],
  ['/', 'Search the chat and every terminal on your floor, back to before the office last restarted'],
  [IS_MAC ? '⌘K' : 'Ctrl+K', 'Command palette: type a few letters to find a worker, issue, PR, service, board, teammate or action. Enter opens it, Shift+Enter walks you over to it first'],
  ['V', 'Join voice. In voice, hold V to talk (push to talk): you’re muted once you let go. Leave voice from the ☰ menu'],
  ['M', 'Mute or unmute your mic in voice. ⚙️ Settings can have you join muted, for push to talk'],
  [', .', 'Hörkreis (flrnoh fork): in voice, only who stands in your circle hears you, nobody outside it. , makes it smaller, . bigger (Flüstern 1,5 m bis Megafon 60 m); the ◯ button on the top bar goes through the sizes and says who hears you. Your circle shows on the floor while you talk, anyone else’s while they talk: bright when you’re in it. Two small circles: unter vier Augen'],
  ['Tab', 'The ☰ menu, top right: every window, and what shows on screen. Pin what you use most to the top bar'],
  ['Esc', 'Close any window and get back to looking around'],
  ['Ctrl + [', 'Send Esc to a terminal instead, to close a menu like Claude’s /skills or interrupt Claude. ⎋ Esc in the terminal’s header does the same'],
  ['⚙️', 'Settings (in the ☰ menu): switch between first and third person'],
  // flrnoh fork: the minimap (features/minimap).
  ['🧭', 'The minimap, bottom right, turns with you: the office, the places and the shops round about, and who’s out there. Once the office is out of sight an arrow at its rim points the way back, with how far (the mouse wheel over it zooms). ☰ hides it'],
  ['J', 'The big map (or click the minimap): the whole town and the loop, north up. Drag to look about, the wheel zooms. Click a place or a shop and the minimap points you there; “Zum Büro” for the way back'],
  // flrnoh fork: DER BRECHER, the roller coaster round the office (features/coaster).
  ['🎢', 'Up on the roof, through the gap in the railing by the DJ: DER BRECHER’s station. E on the platform gets you in (E again gets you out before it goes); a few seconds after the first one’s in, it goes: up the lift hill, straight down the facade past the balconies, the loop over the street, through the ground floor’s ceiling past the desks, straight up the back and home. H (or Space) hands up, the mouse looks round. The photo from the bottom of the drop hangs on the monitor at the station (E there to save it)'],
  // flrnoh fork: the bowling centre's karaoke bar (features/karaoke).
  ['🎤', 'Karaoke in the bowling centre: E at a song book (on the tables and the KJ desk by the stage) puts you on the list with one of the bar’s own songs or a YouTube karaoke link. When it’s your turn, step onto the stage and E at a mic stand; mic 2 is for a duet. On the stage with a mic, everyone in the centre hears you at full volume (voice chat: V). In the bar B claps and Shift+B cheers, 1–5 rates a song when it’s over, and the board by the stage crowns the week’s karaoke king or queen'],
  // flrnoh fork: the bowling centre (client/bowling).
  ['🎳', 'Right next to the office to the east, the bowling centre: E at its glass doors goes in, E at the doors inside back out (everyone from every floor meets in there). E at the counter for a beer from the tap, a Spezi, Pommes rot-weiß or a Currywurst; E at the end of the counter rents bowling shoes in your size (they stay there when you leave). E on a sofa in the lounge sits you down. The big lever by the lounge switches cosmic bowling on and off for everyone: house lights down, black light, mirror ball'],
  // flrnoh fork: the bowling centre's black-light mini golf (features/minigolf).
  ['⛳', 'Black-light mini golf in the bowling centre (the door past the lounge): E at “Schläger & Bälle” takes a putter and a ball in a colour of your own. E at the first tee starts a round, with everyone there who has a putter (you take turns), or just putt away alone. E along your hole puts you over your ball: the mouse or A D aims, hold Space and let go to putt. Nine holes, from a windmill and a loop to a volcano and a pinball table; 7 strokes at most, then it’s a “+” (Q picks the ball up). Tab: the scorecard, best rounds and holes in one'],
  // flrnoh fork: the bowling centre's lanes (features/bowlinggame).
  // flrnoh fork: the Schallwerk's instruments (features/instruments).
  ['🥁', 'The Schallwerk’s stage and rehearsal rooms: E at an instrument plays it (one player each; the key map shows bottom left). Drums: Space kick, F J snare, D K hats, S L open hat, R T G H toms, Q P crash, W O ride, Shift accents; 1–5 a groove to play over, ↑ ↓ the tempo, N the click, B counts in. Guitar: 1–8 strum the key’s chords, Space and B strum again, Shift palm-mutes, A … Ä and Q … P a pentatonic, V the distortion, C power chords or full ones, ← → the room’s key, M major or minor; the bass the same, its 1–8 the chords’ roots. Keyboard: Y … - and Q … + two and a half octaves, Space the sustain pedal, ← → the octave, ↑ ↓ piano, e-piano, organ, synth lead or pad. A mic puts your voice on the room’s PA (the stage’s: the whole hall). Everyone in the room hears you, nobody outside it; E (Esc, Backspace on the keyboard) stops'],
  ['🏆', 'Bowling: E at a lane’s console joins its game (up to six; X leaves), E at the ball return picks a house ball (8–16 lbs). When you’re up, E on the approach: the mouse sets the line, A D and W S move your mark, hold Space (or the mouse button) and let go in the meter, moving the mouse while you hold winds in the hook. Step over the foul line and it’s a foul. The office counts every pin; strikes, spares and splits on the monitors, the week’s league and the all-time records on the board by the wall (E there)'],
];
